# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        ""
url:            "https://Microsoft.github.io/PowerBI-visuals"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              PowerBI Custom Visuals
description:        "PowerBI Custom Visuals Developers Documenation"    
authors:            "Microsoft"
social_image_path:  /assets/brand/bootstrap-social.png
social_logo_path:   /assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      4.0.0
current_ruby_version: 4.0.0
docs_version:         latest
repo:                 "https://github.com/Microsoft/PowerBI-visuals"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
  popper_hash:      "sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"

toc:
  min_level:        2
  max_level:        4
